### ISSUE TITLE
Incorporate Font Awesome for icon usage

### ISSUE THREAD

**Issue by iamamonte** [Turnout-Activism/ReactPlayground#45]
This will be relevant to many different components. Let's bring font awesome into the project and make a base component that essentially just wraps an icons. We can make a generic icon component that takes the "image source" and a function to execute on click as props.

**Comment by sonias02** [comment]
I’ve been researching font awesome and react icons. React icons is a collection of icons from various different locations including font awesome. It is more popular, includes more icon options, and is easy to use, so I suggest we use react icons for this project instead of font awesome. ([https://react-icons.github.io/react-icons/](https://react-icons.github.io/react-icons/)).

**Comment by iamamonte** [comment]
React icons will be used.
